# 5 Easy Functions Of NumPy


### NumPy is a numerical python library which contains multi-dimensional arrays and matrix data structures.

### FUNCTIONS: 

- Function 1 - np.flip()
- Function 2 - np.maximum()
- Function 3 - np.split()
- Function 4 - np.insert()
- Function 5 - np.dot()

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Creating a new project "charvyjain3/numpy-array-operations"
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charvyjain3/numpy-array-operations


'https://jovian.ml/charvyjain3/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [27]:
# List of functions explained 
function1 = np.flip()
function2 = np.maximum()
function3 = np.split()
function4 = np.insert()
function5 = np.dot()

TypeError: _flip_dispatcher() missing 1 required positional argument: 'm'

## Function 1 - np.flip

It reverses the order of elements in array preserving the shape along the axis.

In [49]:
# Example 1 - working (change this)
arr1 = np.array([[5, 6, 7], 
        [8, 9, 10]])

np.flip(arr1, [0])

array([[ 8,  9, 10],
       [ 5,  6,  7]])

In the above exmaple, the elements are flipped along x-axis which means rows are flippped.

In [14]:
# Example 2 - working
arr2 =np.array([[1, 56,2], 
        [6, 4,46],
        [8,22,7]])

np.flip(arr2, [1])

array([[ 2, 56,  1],
       [46,  4,  6],
       [ 7, 22,  8]])

Explanation about example: the elements are flipped along y-axis i.e. column wise elements.

In [50]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = np.array([[1, 2, 8], 
        [3, 4, 6],
       [5, 25, 36]])

np.flip(arr3, [2])

AxisError: axis 2 is out of bounds for array of dimension 2

Explanation about example: The above operation is showing error because we can't flip the elements alonf z- axis which means we can flip either row wise or column wise.

This Flip function can be used to flip the elements.

In [16]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charvyjain3/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charvyjain3/numpy-array-operations


'https://jovian.ml/charvyjain3/numpy-array-operations'

## Function 2 - np.maximum

It compares the given two arrays and gives the output array containing the maxima of elements.

In [17]:
# Example 1 - working
arr1 = [8,9,5]
arr2 = [15,6,1]

np.maximum(arr1, arr2)

array([15,  9,  5])

Explanation about example: In the first column of 2 arrays, 15 is maximum. Like wise in other two columns 9 and 5 are maximum.

In [24]:
# Example 2 - working
arr1 = [[1, 14], 
        [89, 5]]

arr2 = [[23, 6], 
        [1,10]]

np.maximum(arr1, arr2)

array([[23, 14],
       [89, 10]])

Explanation about example: In this (2*2) matrix, the comparision will be held list wise which means [1, 14] in arr1 and [23.6] in arr2 are compared and give us the maximum number.

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[5, 8, 36], 
        [14, 56, 10]]

arr2 = [[25, 36], 
        [3, 58]]

np.maximum(arr1, arr2)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

Explanation about example: This function should only be done when the matrices are of same dimension.

Some closing comments about when to use this function.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charvyjain3/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charvyjain3/numpy-array-operations


'https://jovian.ml/charvyjain3/numpy-array-operations'

## Function 3 - np.split

This function is used to split an array into multiple sub-arrays.

In [29]:
# Example 1 - working
x = np.array([[85,12,33],
             [96,63,56]])

np.split(x, 2, axis=0)

[array([[85, 12, 33]]), array([[96, 63, 56]])]

Explanation about example: The arrays are splitted into two equal parts along the x-axis.

In [31]:
# Example 2 - working
x = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

np.split(x,(2,2),axis=1)

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([], shape=(3, 0), dtype=int64),
 array([[3],
        [6],
        [9]])]

Explanation about example: First the array is splitted in (2,2) shape along y-axis and the last column is splitted as shown above. 

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.array([[99, 98, 97],
               [96, 95, 94]])

np.split(x, 2, axis=1)

ValueError: array split does not result in an equal division

Explanation about example: The array should be splitted in equal parts. If we change the parameter to 3 the code will run.

In [37]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charvyjain3/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charvyjain3/numpy-array-operations


'https://jovian.ml/charvyjain3/numpy-array-operations'

## Function 4 - np.insert

With this function we can insert element along the given axis before the given indices.

In [38]:
# Example 1 - working
c = np.array([[11, 22],
              [35, 64],
              [58, 63]])

np.insert(c, 2, 30, axis=0)

array([[11, 22],
       [35, 64],
       [30, 30],
       [58, 63]])

Explanation about example: Along x- axis means row wise 30 is inserted before row index 2.

In [40]:
# Example 2 - working
c= np.array([[36, 25, 69],
             [56, 23, 20],
             [96, 56, 53]])

np.insert(c, 1, 96, axis=1)

array([[36, 96, 25, 69],
       [56, 96, 23, 20],
       [96, 96, 56, 53]])

Explanation about example: Insert the value 96 column wise before the column index 1.

In [41]:
# Example 3 - breaking (to illustrate when it breaks)
c = np.array([[88, 66],
              [99, 33], 
              [33, 55]])

np.insert(c, 8, 77, axis=1)

IndexError: index 8 is out of bounds for axis 1 with size 2

Explanation about example: The index of given array is 2 only. But we gave index which is greater than 2. The index should be less than or equal to given array.

In [42]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charvyjain3/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charvyjain3/numpy-array-operations


'https://jovian.ml/charvyjain3/numpy-array-operations'

## Function 5 - np.dot

This function gives the dot product of two arrays.

In [43]:
# Example 1 - working
arr1 = np.array([9, 8, 7])
arr2 = np.array([6, 5, 4])

np.dot(arr1, arr2)

122

Explanation about example: This function multiplies the corresponding elements and then adds them to give dot product.

In [45]:
# Example 2 - working
arr1 = np.array([6j, 36j, 69j])
arr2 = np.array([25j, 14j, 23j])

np.dot(arr1, arr2)

(-2241+0j)

Explanation about example: neither argument is complex - cojugated.

In [46]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([56, 58, 58])
arr2 = np.array([56, 22])

np.dot(arr1, arr2)

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

Explanation about example: The dimension of the given two arrays must match to get dot product.

In [47]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charvyjain3/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charvyjain3/numpy-array-operations


'https://jovian.ml/charvyjain3/numpy-array-operations'

## Conclusion

We saw the basic five functions used in NumPy 
- np.flip
- np.maximum
- np.split
- np.insert
- np.dot

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charvyjain3/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
