# 5 Useful And Easy Tensor Functions

PyTorch is a library based on torch library that works on tensors and is used used for applications such as computer vision and natural language processing.
The torch package contains data structures for multi-dimensional tensors and mathematical operations over these are defined.
#### Here are the 5 easy tensor functions :

- torch.transpose
- torch.sort
- torch.mean
- torch.chunk
- torch.det

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 159.3MB 91kB/s 
     |████████████████████████████████| 11.8MB 22.9MB/s 
     |████████████████████████████████| 7.6MB 3.8MB/s 
  Found existing installation: torch 1.7.0+cu101
    Uninstalling torch-1.7.0+cu101:
      Successfully uninstalled torch-1.7.0+cu101
  Found existing installation: torchvision 0.8.1+cu101
    Uninstalling torchvision-0.8.1+cu101:
      Successfully uninstalled torchvision-0.8.1+cu101


In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.transpose

**This function returns the transpose of the given tensor.**

In [4]:
x = torch.tensor([[ 2.628, -0.98,  60.9],
        [5.1669,  2.99,  -0.4942]])

torch.transpose(x, 0, 1)

tensor([[ 2.6280,  5.1669],
        [-0.9800,  2.9900],
        [60.9000, -0.4942]])

Here, We obtained a tensor where the rows and columns are interchanged.

In [ ]:
y = torch.tensor([[3.72,  12.225]])

torch.transpose(y, 0, 1)

tensor([[ 3.7200],
        [12.2250]])

We should give two parameters namely dim0 and dim1. These given dimensions will be swapped.

In [ ]:
x = torch.tensor([[ 2.628, -0.98,  60.9],
        [5.1669,  2.99,  -0.4942]])

torch.transpose(x, 0, 2)

IndexError: ignored

We sholud not give the dimensions which are out of range. This will cause IndexError.

This function is very useful to deal with common problems in the field of linear algebra.

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [6]:
import jovian

In [5]:
jovian.commit(project='5-Useful-And-Easy-Tensor-Functions')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/charvyjain3/5-useful-and-easy-tensor-functions


'https://jovian.ai/charvyjain3/5-useful-and-easy-tensor-functions'

## Function 2 - torch.sort


**This funtcion sorts the given tensor along a given dimension. By default, it sorts in ascending order.**

In [ ]:
x = torch.tensor([[0.22,  0.0608,  6.719,  2.3332],
        [0.93,  -0.01,  0.68,  0.947],
        [0.5071,  0.43,  -0.553,  -1.0960]])

sorted, indices = torch.sort(x)
print(sorted)

tensor([[ 0.0608,  0.2200,  2.3332,  6.7190],
        [-0.0100,  0.6800,  0.9300,  0.9470],
        [-1.0960, -0.5530,  0.4300,  0.5071]])


As expected, this function returned a tensor with the values being sorted in ascending order.

In [ ]:
y = torch.tensor([[50.71, 0.22,  0.6719, -0.93],
        [ 0.608,  -0.0061,  -0.9497,  0.33],
        [ 0.58,  -0.9553,  1.0960,  -2.3332]])

sorted, indices = torch.sort(x, 1)
print(sorted)
print(indices)

tensor([[ 0.0608,  0.2200,  2.3332,  6.7190],
        [-0.0100,  0.6800,  0.9300,  0.9470],
        [-1.0960, -0.5530,  0.4300,  0.5071]])
tensor([[1, 0, 3, 2],
        [1, 2, 0, 3],
        [3, 2, 1, 0]])


The ourput tensor has values which are the sorted and indices are indices of the elements in the original input tensor. That's why there are jumbled.
We had specified the dimension to sort along.

In [ ]:
a = torch.tensor([98, 36, 56, 21, 39, 76, 36])
torch.sort(a, 1)

IndexError: ignored

This error is shown because dimensional parameter has the value which does not exist for the tensor dimension. We have to be careful when giving the dimensional parameter.

This function is used to get a sorted data in ascending or descending order for our further calculations.

In [7]:
jovian.commit(project='5-Useful-And-Easy-Tensor-Functions')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/charvyjain3/5-useful-and-easy-tensor-functions


'https://jovian.ai/charvyjain3/5-useful-and-easy-tensor-functions'

## Function 3 - torch.mean

**It returns the mean value of all elements in the input tensor.**

In [ ]:
x = torch.tensor([[ 0.2294, -0.5481,  1.3288]])

torch.mean(x)

tensor(0.3367)

Here we have got the mean value of the given tensor.

In [ ]:
y = torch.tensor([[ 4.19,  -0.743, -0.6921, -0.2577],
        [-1.8135,  3.8, -0.76,  0.1105],
        [ 0.01, -0.88, 7.07,  0.80]])

torch.mean(y, 1)

tensor([0.6243, 0.3342, 1.7500])

Here, We have given paramenter to reduce the dimension of output tensor.

In [ ]:
y = torch.tensor([[ 4.19,  -0.743, -0.6921, -0.2577],
        [-1.8135,  3.8, -0.76,  0.1105],
        [ 0.01, -0.88, 7.07,  0.80]])

torch.mean(y, 3 , keepdim=False) 

IndexError: ignored

The range should be in between -2 to 1.

This function is used to calculate the mean of the given tensor.

In [8]:
jovian.commit(project='5-Useful-And-Easy-Tensor-Functions')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/charvyjain3/5-useful-and-easy-tensor-functions


'https://jovian.ai/charvyjain3/5-useful-and-easy-tensor-functions'

## Function 4 - torch.chunk 

**This function splits a tensor into a specific number of chunks (splitting). Each chunk is a view of the input tensor.**

In [ ]:
x = torch.tensor([6.3, 69, 3.6, 56, 42, 89])

torch.chunk(x, 3, dim=0) 

(tensor([ 6.3000, 69.0000]), tensor([ 3.6000, 56.0000]), tensor([42., 89.]))

We have given parameter 3, so the given tensor was splitted into 3 different smaller tensors.

In [ ]:
y = torch.tensor([300, 35, 563, 40, 5, 70, 75, 80, 80, 96])

torch.chunk(y, 3, 0)

(tensor([300,  35, 563,  40]), tensor([ 5, 70, 75, 80]), tensor([80, 96]))

Note that the third tensor has only two elements instead of three. This happens becaues the total values for the given tensor is odd number.

In [ ]:
r = torch.tensor([[2.0 , 5, 7, 5, 77, 2142, 11],[55, 67.96, 43]])

torch.chunk(r, 4, dim=0) 

ValueError: ignored

Length of all the dim should be same.

This function can be used to manipulate the data of the tensors according to our needs.

In [ ]:
jovian.commit(project='5-Useful-And-Easy-Tensor-Functions')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/charvyjain3/5-useful-and-easy-tensor-functions


'https://jovian.ai/charvyjain3/5-useful-and-easy-tensor-functions'

## Function 5 - torch.det

**This function calculates determinant of a square matrix.**

In [ ]:
x = torch.tensor([[86, 3.6], [96.3, 89]])

torch.det(x)

tensor(7307.3203)

The determinent of given tensor is 7307.3203

In [ ]:
y = torch.tensor([[[ 0.9254, -0.6213],
         [-0.5787,  1.6843]],

        [[ 0.3242, -0.9665],
         [ 0.4539, -0.0887]],

        [[ 1.1336, -0.4025],
         [-0.7089,  0.9032]]])
torch.det(y)

tensor([1.1991, 0.4099, 0.7385])

The determinant is calculated by calculating the determinant for each square matrix.

In [ ]:
x = torch.tensor([[1, 2], [1, 2, 3]])

torch.det(x)

ValueError: ignored

In order to calculate the determinant, the matrix should be square.

This function is used for finding determinants of the square matrices.

In [ ]:
jovian.commit(project='5-Useful-And-Easy-Tensor-Functions')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion

This notebook covered 5 tensor functions which are simple yet very powerful thst will help us.There are several other interesting functions to check on.

1. **torch.transpose() - returns the transpose**
2. **torch.sort() -  sorts the given tensor**
3. **torch.mean() - returns the mean value**
4. **torch.chunk() - splits a tensor**
5. **torch.det() - calculates determinant**



## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html

In [9]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/charvyjain3/01-tensor-operations


'https://jovian.ai/charvyjain3/01-tensor-operations'